// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnwfgwahbiwaxhigmdkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFud2Znd2FoYml3YXhoaWdtZGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjA2MDYsImV4cCI6MjA2OTk5NjYwNn0.7vnmOKSrHu5VB70iV_O8o_mXW7RpCtR5m2qZxpTgGZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});